version: 2
jobs:
  build:
    working_directory: ~/AppAlerts
    docker:
      - image: cimg/android:2023.02
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "SnackBars/build.gradle" }}
      #      - run:
      #         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
      #         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "SnackBars/build.gradle" }}
      - run:
          name: Run Presentation Module Unit Tests
          command: ./gradlew :SnackBars:testDebugUnitTest
      - store_artifacts:
          path: SnackBars/build/reports
      - store_test_results:
          path: SnackBars/build/test-results
      - run:
          name: Run Domain Module Unit Tests
          command: ./gradlew :SnackBars:test
      - store_artifacts:
          path: domain/build/reports
      - store_test_results:
          path: domain/build/test-results
      - run:
          name: Run Data Module Unit Tests
          command: ./gradlew :SnackBars:testDebugUnitTest
      - store_artifacts:
          path: data/build/reports
      - store_test_results:
          path: data/build/test-results
      - run:
          name: Run Lint Test
          command: ./gradlew lint
      - run:
          name: Deploy to JitPack plaes
          command:| curl -X POST -H "Authorization: token jp_8djsq5v2shrm9q25b8e9djm41d" https://jitpack.io/api/builds/com.snackbars/snackbars/0.1.0-SNAPSHOT
      - store_artifacts:
          path: SnackBars/build/reports